#!/bin/sh
#
# @name Gazebo TL4Q990-class 3D lidar
#
# @type Quadrotor
#

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=tl4q990_3d_lidar}

param set-default SIM_GZ_EN 1

# The ROS/MAVROS bridge is the single external-odometry source for this model.
# Disable GZBridge's direct vehicle_visual_odometry publisher to avoid feeding
# EKF2 the same motion in a different origin and pose frame.
param set-default SIM_GZ_EN_ODOM 0

param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 4

# PX4 uses front-right-down coordinates. The matching Gazebo model uses
# front-left-up, hence the opposite signs for the SDF y coordinates.
param set-default CA_ROTOR0_PX 0.35
param set-default CA_ROTOR0_PY 0.35
param set-default CA_ROTOR0_KM 0.03

param set-default CA_ROTOR1_PX -0.35
param set-default CA_ROTOR1_PY -0.35
param set-default CA_ROTOR1_KM 0.03

param set-default CA_ROTOR2_PX 0.35
param set-default CA_ROTOR2_PY -0.35
param set-default CA_ROTOR2_KM -0.03

param set-default CA_ROTOR3_PX -0.35
param set-default CA_ROTOR3_PY 0.35
param set-default CA_ROTOR3_KM -0.03

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104

param set-default SIM_GZ_EC_MIN1 120
param set-default SIM_GZ_EC_MIN2 120
param set-default SIM_GZ_EC_MIN3 120
param set-default SIM_GZ_EC_MIN4 120

param set-default SIM_GZ_EC_MAX1 800
param set-default SIM_GZ_EC_MAX2 800
param set-default SIM_GZ_EC_MAX3 800
param set-default SIM_GZ_EC_MAX4 800

# 0.55 maps to roughly 494 rad/s with the output range above. Together with
# the SDF thrust coefficient this balances the 6.5 kg model near hover.
param set-default MPC_THR_HOVER 0.55

# The larger inertia and slower motors benefit from conservative initial rate
# gains. These are starting points, not identification results for real hardware.
param set-default MC_ROLLRATE_P 0.12
param set-default MC_ROLLRATE_I 0.15
param set-default MC_ROLLRATE_D 0.002
param set-default MC_PITCHRATE_P 0.12
param set-default MC_PITCHRATE_I 0.15
param set-default MC_PITCHRATE_D 0.002
param set-default MC_YAWRATE_P 0.12
param set-default MC_YAWRATE_I 0.02

param set-default NAV_DLL_ACT 2
